/**
  * 题目Id：389
  * 题目：Find the Difference
  * 日期：2022-02-24 17:35:53
*/
//You are given two strings s and t. 
//
// String t is generated by random shuffling string s and then add one more 
//letter at a random position. 
//
// Return the letter that was added to t. 
//
// 
// Example 1: 
//
// 
//Input: s = "abcd", t = "abcde"
//Output: "e"
//Explanation: 'e' is the letter that was added.
// 
//
// Example 2: 
//
// 
//Input: s = "", t = "y"
//Output: "y"
// 
//
// 
// Constraints: 
//
// 
// 0 <= s.length <= 1000 
// t.length == s.length + 1 
// s and t consist of lowercase English letters. 
// 
// Related Topics 位运算 哈希表 字符串 排序 👍 302 👎 0

package leetcode.editor.cn;
public class FindTheDifference {
    public static void main(String[] args) {
        Solution solution = new FindTheDifference().new Solution();
        System.out.println("Hello world");
    }
    //leetcode submit region begin(Prohibit modification and deletion)
class Solution {
    public char findTheDifference(String s, String t) {
        int[] cnt = new int[26];
        for (char c : s.toCharArray()) {
            cnt[c - 'a']++;
        }
        for (char ct : t.toCharArray()) {
            cnt[ct - 'a']--;
            if (cnt[ct - 'a'] < 0) {
                return ct;
            }
        }
        return ' ';
    }
}
//leetcode submit region end(Prohibit modification and deletion)

} 
